services:
  - type: web
    name: license-server
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
      - key: MONGODB_URI
        sync: false

